# Netlify configuration for Chess Memory

[build]
  publish = "."

# Redirect rules for clean URLs
[[redirects]]
  from = "/about"
  to = "/about.html"
  status = 200

[[redirects]]
  from = "/faq"
  to = "/about.html"
  status = 200

# 404 redirect to home page
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 404

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

